config/routes.rb
Rails.application.routes.draw do

	root 'authors#new'
	get 'nice_books/all', to: 'books#index', :defaults => { :format => :json }
	get 'authors/new_author', to: 'authors#new'
	get 'authors/:id', to: 'authors#show', as: :author
	post 'authors', to: 'authors#create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  
  extend FriendlyId
  friendly_id :last_name, use: [:slugged, :history]

  #Validations
  validates :first_name, :last_name, presence: true, allow_blank: true
  validates :last_name, uniqueness: true
  validates_format_of :last_name, :with => /\A[a-z0-9]+\z/i

  #Associations
  has_many :books

end

app/models/book.rb
class Book < ApplicationRecord
  
  #Call backs
  before_save :populate_short_name

  #Validations
  validates :full_name, presence: true, allow_blank: true

  #Associations
  belongs_to :author, optional: true

  private
  def populate_short_name
  	self.short_name = full_name.downcase.tr(" ", "_")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.friendly.find(params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :author_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :author_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

app/views/layouts/_head.html.erb
<%= link_to 'Books' ,nice_books_all_path %>
<%= link_to 'New author' ,authors_new_author_path %>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/head" %>
    <%= yield %>
  </body>
</html>